const nodeCrypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { chromium } = require("playwright");

const REPO_ROOT = path.resolve(__dirname, "../../..");
const TARGET_URL = process.env.TARGET_URL || "http://127.0.0.1:5173";
const API_BASE_URL = (process.env.BUTTON_AUDIT_API_BASE_URL || process.env.VITE_API_BASE_URL || "http://127.0.0.1:8000/api/v1").replace(/\/$/, "");
const RESULTS_ROOT = process.env.RESULTS_DIR || path.join(REPO_ROOT, "testing", "button-audit");
const HEADLESS = process.env.HEADLESS !== "false";
const CLICK_TIMEOUT = Number(process.env.BUTTON_AUDIT_CLICK_TIMEOUT || 5000);
const POST_CLICK_WAIT_MS = Number(process.env.BUTTON_AUDIT_POST_CLICK_WAIT_MS || 700);
const FIXTURE_PROJECT_NAME = process.env.BUTTON_AUDIT_PROJECT_NAME || "Button Audit Fixture";
const FAIL_ON_STALE = process.env.FAIL_ON_STALE === "true";

const BUTTON_SELECTOR = [
  "button",
  "[role='button']",
  "input[type='button']",
  "input[type='submit']",
  "input[type='reset']",
].join(", ");

const ONE_PIXEL_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=",
  "base64",
);

function absoluteUrl(pagePath) {
  return new URL(pagePath, TARGET_URL).toString();
}

function hash(value) {
  return nodeCrypto.createHash("sha256").update(value).digest("hex").slice(0, 16);
}

function normalizeText(value) {
  return value.replace(/\s+/g, " ").trim();
}

function ensureDir(directory) {
  fs.mkdirSync(directory, { recursive: true });
}

async function waitForAppSettled(page) {
  await page.waitForLoadState("domcontentloaded").catch(() => undefined);
  await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => undefined);
  await page.waitForTimeout(250);
}

async function defaultPrepare(page, pagePath) {
  await page.goto(absoluteUrl(pagePath), { waitUntil: "domcontentloaded" });
  await waitForAppSettled(page);
}

async function pageShowsProjectNotFound(page) {
  return page.evaluate(() => /project not found/i.test(document.body.innerText || ""));
}

async function requestJson(apiPath, init = {}) {
  const response = await fetch(`${API_BASE_URL}${apiPath}`, init);
  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(`HTTP ${response.status} from ${apiPath}${text ? `: ${text.slice(0, 240)}` : ""}`);
  }
  return response.status === 204 ? null : response.json();
}

async function listPagesForProject(projectId) {
  try {
    return await requestJson(`/projects/${projectId}/pages`);
  } catch {
    return [];
  }
}

async function createHttpFixtureProject() {
  const project = await requestJson("/projects", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: `${FIXTURE_PROJECT_NAME} ${new Date().toISOString()}`,
      description: "Generated by frontend button audit.",
      source_language: "auto",
      target_language: "en",
      translation_tone: "natural",
      replacement_mode: "replace",
      reading_direction: "rtl",
    }),
  });

  const formData = new FormData();
  formData.append(
    "files",
    new Blob([ONE_PIXEL_PNG], { type: "image/png" }),
    "button-audit-page.png",
  );
  await requestJson(`/projects/${project.id}/pages/upload`, {
    method: "POST",
    body: formData,
  });

  return project.id;
}

async function ensureHttpProjectFixture() {
  if (process.env.BUTTON_AUDIT_PROJECT_ID) {
    return process.env.BUTTON_AUDIT_PROJECT_ID;
  }

  const projects = await requestJson("/projects");
  for (const project of projects) {
    if (!project.name?.startsWith(FIXTURE_PROJECT_NAME)) {
      continue;
    }
    const pages = await listPagesForProject(project.id);
    if (pages.length > 0) {
      return project.id;
    }
  }

  return createHttpFixtureProject();
}

function projectRoute(routeName, mockProjectId = "project-cyber") {
  return async (page) => {
    let httpProjectId = null;
    try {
      httpProjectId = await ensureHttpProjectFixture();
    } catch {
      httpProjectId = null;
    }

    if (httpProjectId) {
      await defaultPrepare(page, `/projects/${httpProjectId}/${routeName}`);
      if (!(await pageShowsProjectNotFound(page))) {
        return;
      }
    }

    const mockPath = `/projects/${mockProjectId}/${routeName}`;
    await defaultPrepare(page, mockPath);
    if (!(await pageShowsProjectNotFound(page))) {
      return;
    }

    throw new Error(
      `Unable to prepare ${routeName} audit. Set BUTTON_AUDIT_PROJECT_ID or run with a seeded mock project.`,
    );
  };
}

async function projectSetupWithFixture(page) {
  await page.goto(absoluteUrl("/"), { waitUntil: "domcontentloaded" });
  await page.setInputFiles("input[type='file']", {
    name: "button-audit-page.png",
    mimeType: "image/png",
    buffer: ONE_PIXEL_PNG,
  });
  await page.waitForURL("**/projects/new", { timeout: 10000 });
  await waitForAppSettled(page);
}

async function snapshot(page) {
  return page.evaluate((buttonSelector) => {
    const text = document.body.innerText || "";
    const buttons = Array.from(document.querySelectorAll(buttonSelector)).map((element, index) => ({
      index,
      label:
        element.getAttribute("aria-label") ||
        element.textContent?.replace(/\s+/g, " ").trim() ||
        element.getAttribute("title") ||
        element.getAttribute("value") ||
        element.tagName.toLowerCase(),
      ariaExpanded: element.getAttribute("aria-expanded"),
      ariaPressed: element.getAttribute("aria-pressed"),
      ariaCurrent: element.getAttribute("aria-current"),
      className:
        typeof element.className === "string"
          ? element.className
          : element.getAttribute("class") || "",
      disabled:
        element.hasAttribute("disabled") ||
        element.getAttribute("aria-disabled") === "true",
    }));

    return {
      url: window.location.href,
      title: document.title,
      text,
      html: document.body.innerHTML,
      buttons,
    };
  }, BUTTON_SELECTOR);
}

function summarizeSnapshot(raw) {
  const text = normalizeText(raw.text);
  return {
    url: raw.url,
    pathname: new URL(raw.url).pathname + new URL(raw.url).search,
    title: raw.title,
    textHash: hash(text),
    htmlHash: hash(raw.html),
    textExcerpt: text.slice(0, 600),
    buttonStateHash: hash(JSON.stringify(raw.buttons)),
  };
}

async function collectButtons(page) {
  return page.locator(BUTTON_SELECTOR).evaluateAll((elements) =>
    elements.map((element, index) => {
      const rect = element.getBoundingClientRect();
      const style = window.getComputedStyle(element);
      const label =
        element.getAttribute("aria-label") ||
        element.textContent?.replace(/\s+/g, " ").trim() ||
        element.getAttribute("title") ||
        element.getAttribute("value") ||
        element.tagName.toLowerCase();
      return {
        index,
        label,
        tagName: element.tagName.toLowerCase(),
        type: element.getAttribute("type"),
        title: element.getAttribute("title"),
        ariaLabel: element.getAttribute("aria-label"),
        ariaExpanded: element.getAttribute("aria-expanded"),
        ariaPressed: element.getAttribute("aria-pressed"),
        ariaCurrent: element.getAttribute("aria-current"),
        disabled:
          element.hasAttribute("disabled") ||
          element.getAttribute("aria-disabled") === "true",
        visible:
          rect.width > 0 &&
          rect.height > 0 &&
          style.visibility !== "hidden" &&
          style.display !== "none",
        rect: {
          x: Math.round(rect.x),
          y: Math.round(rect.y),
          width: Math.round(rect.width),
          height: Math.round(rect.height),
        },
      };
    }),
  );
}

function addLabelOccurrences(buttons) {
  const counts = new Map();
  return buttons.map((button) => {
    const occurrence = counts.get(button.label) ?? 0;
    counts.set(button.label, occurrence + 1);
    return { ...button, labelOccurrence: occurrence };
  });
}

async function getButtonLocator(page, button) {
  const label = button.label?.trim();
  if (label) {
    const byAccessibleName = page.getByRole("button", { name: label, exact: true });
    const matchingCount = await byAccessibleName.count().catch(() => 0);
    if (matchingCount > button.labelOccurrence) {
      return byAccessibleName.nth(button.labelOccurrence);
    }
  }
  return page.locator(BUTTON_SELECTOR).nth(button.index);
}

function classify(before, after, events, actionError, button) {
  if (!button.visible) return "skipped-hidden";
  if (button.disabled) return "skipped-disabled";
  if (!before || !after) return "error";
  if (actionError) return "error";
  const changed =
    before.url !== after.url ||
    before.textHash !== after.textHash ||
    before.htmlHash !== after.htmlHash ||
    before.buttonStateHash !== after.buttonStateHash ||
    events.fileChooser ||
    events.download ||
    events.dialog ||
    events.popup;
  if (changed) return "changed";
  if (button.ariaPressed === "true" || button.ariaCurrent === "true") {
    return "skipped-current";
  }
  return "no-observable-change";
}

function labelMatches(button, expectation) {
  const label = button.label || "";
  if (expectation.label !== undefined && label !== expectation.label) {
    return false;
  }
  if (expectation.pattern !== undefined && !expectation.pattern.test(label)) {
    return false;
  }
  if (expectation.occurrence !== undefined && button.labelOccurrence !== expectation.occurrence) {
    return false;
  }
  return expectation.label !== undefined || expectation.pattern !== undefined;
}

function findButtonExpectation(config, button) {
  return (config.expectedButtons || []).find((expectation) => labelMatches(button, expectation)) || null;
}

function pathMatches(actualPath, expectation) {
  if (expectation.expectedPath !== undefined) {
    return actualPath === expectation.expectedPath;
  }
  if (expectation.expectedPathPattern !== undefined) {
    return expectation.expectedPathPattern.test(actualPath);
  }
  return true;
}

function textContains(after, expectedText) {
  if (expectedText === undefined) {
    return true;
  }
  return Boolean(after?.textExcerpt?.includes(expectedText));
}

function expectationFailure(result) {
  const { expected, button, status, events, after } = result;
  if (!expected) {
    return button.visible ? "Visible button is not classified in the page expectation manifest." : null;
  }

  if (status === "error") {
    return "Button action errored before the expected outcome could be verified.";
  }

  switch (expected.kind) {
    case "disabledExpected":
      return status === "skipped-disabled" ? null : `Expected disabled button, got ${status}.`;
    case "currentSelection":
      return status === "skipped-current" ? null : `Expected current/selected button, got ${status}.`;
    case "intentionalNoop":
      return status === "no-observable-change" ? null : `Expected intentional no-op, got ${status}.`;
    case "opensFileChooser":
      return events.fileChooser ? null : "Expected file chooser event.";
    case "downloads":
      return events.download || textContains(after, expected.expectedText)
        ? null
        : "Expected download event or download-ready UI.";
    case "navigates": {
      if (!after) {
        return "Expected navigation, but no post-click snapshot was available.";
      }
      return pathMatches(after.pathname, expected)
        ? null
        : `Expected navigation to ${expected.expectedPath || expected.expectedPathPattern}, got ${after.pathname}.`;
    }
    case "opensPopover":
      return status === "changed" && textContains(after, expected.expectedText)
        ? null
        : `Expected popover/menu text ${expected.expectedText || "(any observable popover)"}.`;
    case "changesUiState":
    case "mutatesApi":
      return status === "changed" ? null : `Expected observable state/API change, got ${status}.`;
    default:
      return `Unknown expected button kind: ${expected.kind}`;
  }
}

async function auditButton(browser, config, button) {
  const context = await browser.newContext({
    viewport: { width: 1440, height: 1000 },
    permissions: ["clipboard-read", "clipboard-write"],
  });
  const page = await context.newPage();
  const consoleMessages = [];
  const pageErrors = [];
  const requestFailures = [];
  const events = {
    fileChooser: false,
    download: false,
    dialog: false,
    popup: false,
  };

  page.on("console", (message) => {
    if (["error", "warning"].includes(message.type())) {
      consoleMessages.push({ type: message.type(), text: message.text() });
    }
  });
  page.on("pageerror", (error) => {
    pageErrors.push(error.stack || error.message);
  });
  page.on("requestfailed", (request) => {
    requestFailures.push({
      url: request.url(),
      failure: request.failure()?.errorText || "unknown",
    });
  });
  page.on("response", (response) => {
    if (response.status() >= 400 && !response.url().includes("/favicon")) {
      requestFailures.push({ url: response.url(), status: response.status() });
    }
  });

  let before = null;
  let after = null;
  let actionError = null;

  try {
    await config.prepare(page, config.path);
    before = summarizeSnapshot(await snapshot(page));

    if (!button.visible || button.disabled) {
      after = before;
    } else {
      const target = await getButtonLocator(page, button);
      const fileChooserPromise = page
        .waitForEvent("filechooser", { timeout: 1000 })
        .then(() => {
          events.fileChooser = true;
        })
        .catch(() => undefined);
      const downloadPromise = page
        .waitForEvent("download", { timeout: 1000 })
        .then(() => {
          events.download = true;
        })
        .catch(() => undefined);
      const dialogPromise = page
        .waitForEvent("dialog", { timeout: 1000 })
        .then(async (dialog) => {
          events.dialog = true;
          await dialog.dismiss().catch(() => undefined);
        })
        .catch(() => undefined);
      const popupPromise = page
        .waitForEvent("popup", { timeout: 1000 })
        .then(async (popup) => {
          events.popup = true;
          await popup.close().catch(() => undefined);
        })
        .catch(() => undefined);

      await target.scrollIntoViewIfNeeded({ timeout: CLICK_TIMEOUT }).catch(() => undefined);
      await target.click({ timeout: CLICK_TIMEOUT });
      await Promise.all([fileChooserPromise, downloadPromise, dialogPromise, popupPromise]);
      await page.waitForTimeout(POST_CLICK_WAIT_MS);
      await waitForAppSettled(page);
      after = summarizeSnapshot(await snapshot(page));
    }
  } catch (error) {
    actionError = error.stack || error.message;
    try {
      after = summarizeSnapshot(await snapshot(page));
    } catch {
      after = before;
    }
  } finally {
    await context.close();
  }

  const status = classify(before, after, events, actionError, button);
  const result = {
    page: config.pageName,
    button,
    expected: findButtonExpectation(config, button),
    status,
    observableChange: status === "changed",
    before,
    after,
    events,
    actionError,
    consoleMessages,
    pageErrors,
    requestFailures,
  };
  result.expectationFailure = expectationFailure(result);
  return result;
}

function buildMarkdown(config, result) {
  const stale = result.buttons.filter((item) => item.status === "no-observable-change");
  const errors = result.buttons.filter(
    (item) =>
      item.status === "error" ||
      item.consoleMessages.length ||
      item.pageErrors.length ||
      item.requestFailures.length,
  );
  const expectationFailures = result.buttons.filter((item) => item.expectationFailure);

  return [
    `# Button Audit: ${config.pageName}`,
    "",
    `Run time: ${result.completedAt}`,
    `Target: ${TARGET_URL}`,
    `Path: ${config.path}`,
    "",
    "## Summary",
    "",
    `- Total buttons found: ${result.summary.total}`,
    `- Changed something observable: ${result.summary.changed}`,
    `- No observable change: ${result.summary.noObservableChange}`,
    `- Skipped disabled: ${result.summary.skippedDisabled}`,
    `- Skipped hidden: ${result.summary.skippedHidden}`,
    `- Skipped current/selected: ${result.summary.skippedCurrent}`,
    `- Errors or browser issues: ${result.summary.errors}`,
    `- Expectation failures: ${result.summary.expectationFailures}`,
    "",
    "## Likely Stale Buttons",
    "",
    stale.length
      ? stale
          .map(
            (item) =>
              `- #${item.button.index} "${item.button.label}" at ${item.button.rect.x},${item.button.rect.y} (${item.button.rect.width}x${item.button.rect.height})`,
          )
          .join("\n")
      : "None detected.",
    "",
    "## Errors",
    "",
    errors.length
      ? errors
          .map(
            (item) =>
              `- #${item.button.index} "${item.button.label}": ${item.actionError || item.consoleMessages[0]?.text || item.pageErrors[0] || JSON.stringify(item.requestFailures[0])}`,
          )
          .join("\n")
      : "None observed.",
    "",
    "## Expectation Failures",
    "",
    expectationFailures.length
      ? expectationFailures
          .map(
            (item) =>
              `- #${item.button.index} "${item.button.label}": ${item.expectationFailure}`,
          )
          .join("\n")
      : "None observed.",
    "",
    "## Full Results",
    "",
    `See \`${path.relative(REPO_ROOT, result.jsonPath)}\`.`,
    "",
  ].join("\n");
}

async function auditPage(options) {
  const config = {
    prepare: defaultPrepare,
    ...options,
  };
  const outputDir = path.join(RESULTS_ROOT, config.pageName);
  ensureDir(outputDir);

  const browser = await chromium.launch({ headless: HEADLESS, slowMo: HEADLESS ? 0 : 40 });
  let buttons = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    await config.prepare(page, config.path);
    buttons = addLabelOccurrences(await collectButtons(page));
    await context.close();

    const results = [];
    for (const button of buttons) {
      const result = await auditButton(browser, config, button);
      results.push(result);
      console.log(`${config.pageName}: #${button.index} "${button.label}" -> ${result.status}`);
    }

    const completedAt = new Date().toISOString();
    const summary = {
      total: results.length,
      changed: results.filter((item) => item.status === "changed").length,
      noObservableChange: results.filter((item) => item.status === "no-observable-change").length,
      skippedDisabled: results.filter((item) => item.status === "skipped-disabled").length,
      skippedHidden: results.filter((item) => item.status === "skipped-hidden").length,
      skippedCurrent: results.filter((item) => item.status === "skipped-current").length,
      errors: results.filter(
        (item) =>
          item.status === "error" ||
          item.consoleMessages.length ||
          item.pageErrors.length ||
          item.requestFailures.length,
      ).length,
      expectationFailures: results.filter((item) => item.expectationFailure).length,
    };
    const jsonPath = path.join(outputDir, "button-audit.json");
    const reportPath = path.join(outputDir, "button-audit.md");
    const payload = {
      pageName: config.pageName,
      path: config.path,
      targetUrl: TARGET_URL,
      startedAt: new Date().toISOString(),
      completedAt,
      summary,
      buttons: results,
      jsonPath,
    };
    fs.writeFileSync(jsonPath, JSON.stringify(payload, null, 2));
    fs.writeFileSync(reportPath, buildMarkdown(config, payload));

    if (summary.expectationFailures > 0) {
      process.exitCode = 3;
    } else if (FAIL_ON_STALE && summary.noObservableChange > 0) {
      process.exitCode = 2;
    }
    return payload;
  } finally {
    await browser.close();
  }
}

module.exports = {
  auditPage,
  prepares: {
    defaultPrepare,
    projectRoute,
    projectSetupWithFixture,
  },
};
